spring:
  application:
    name: llm4j
deepseek:
  api-key: your-api-key-here
  model: deepseek-r1:14b
  base-url: http://127.0.0.1:11434/v1
#  base-url: https://api.siliconflow.cn/v1
#  model: deepseek-ai/DeepSeek-R1
#  api-key: sk-qjweznhmxdeiqwwutdpxbwrqdzgrdqzvjcddveivdkbscagu
#  log-requests: true
#  log-responses: true
#  log-level: debug
server:
  port: 9001
#logging:
#  level:
#    root: debug

langchain4j:
  open-ai:
    chat-model:
      model-name: qwen3:14b
      base-url: http://127.0.0.1:11434/v1
      api-key: your-api-key-here
    streaming-chat-model:
      model-name: qwen3:14b
      base-url: http://127.0.0.1:11434/v1
      api-key: your-api-key-here