spring:
  application:
    name: langchain4j-high
server:
  port: 9002
langchain4j:
  open-ai:
      chat-model:
        model-name: qwen3:14b
        base-url: http://127.0.0.1:11434/v1
        api-key: your-api-key-here
      streaming-chat-model:
        model-name: qwen3:14b
        base-url: http://127.0.0.1:11434/v1
        api-key: your-api-key-here